name: Android CI

version: 2
jobs:
  build-and-test:
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Fix for SDK licences not accepted (see https://bit.ly/2AT5G8o)
          command: yes | sdkmanager --licenses || yes | sdkmanager --update || exit 0
      - run:
          name: Install Build Tools
          command: echo y | sdkmanager "build-tools;27.0.3"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Android Lint
          command: ./gradlew lintDevDebug -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Run ktlint
          command: ./gradlew ktlint -PpreDexEnable=false -PdisablePreDex --max-workers 1 --console=plain --no-daemon
      - run:
          name: Run detekt
          command: ./gradlew detektCheck -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Run Checkstyle
          command: ./gradlew checkstyle -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Run Findbugs
          command: ./gradlew findbugs -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Run PMD
          command: ./gradlew pmd -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Run Tests
          command: ./gradlew jacocoTestReport -PdisablePreDex -Pcoverage --console=plain;
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results
          - run: ./gradlew assembleDevRelease -PdisablePreDex
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - app/build/outputs/apk/dev/release
            - config
            - .shaman.yml


workflows:
  version: 1
  build:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
